# Generated by Django 2.1.10 on 2019-07-17 17:31

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newslink',
            options={'get_latest_by': 'pub_date', 'ordering': ['-pub_date'], 'verbose_name': 'news article'},
        ),
        migrations.AlterField(
            model_name='newslink',
            name='slug',
            field=models.SlugField(max_length=63),
        ),
        migrations.AlterField(
            model_name='newslink',
            name='title',
            field=models.CharField(max_length=63),
        ),
        migrations.AlterField(
            model_name='startup',
            name='slug',
            field=models.SlugField(help_text='A label for URL config.', max_length=31, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, help_text='A label for URL config.', max_length=31, populate_from=['name']),
        ),
    ]
